# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-1-13:

    name: Build and test (Elixir 1.13; Erlang 25)
    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwxgtk3.0-gtk3-dev
        version: 1.0
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18.1
      with:
        elixir-version: '1.13.4'
        otp-version: '25.3.2.12'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: mix test

  build-1-14:

    name: Build and test (Elixir 1.14; Erlang 25)
    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwxgtk3.0-gtk3-dev
        version: 1.0
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18.1
      with:
        elixir-version: '1.14.5'
        otp-version: '25.3.2.12'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: mix test

  build-1-15:

    name: Build and test (Elixir 1.15; Erlang 26)
    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwxgtk3.0-gtk3-dev
        version: 1.0
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18.1
      with:
        elixir-version: '1.15.2'
        otp-version: '26.2.5.3'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: mix test

  build-1-16:

    name: Build and test (Elixir 1.16; Erlang 26)
    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwxgtk3.0-gtk3-dev
        version: 1.0
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18.1
      with:
        elixir-version: '1.16.3'
        otp-version: '26.2.5.3'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: mix test

  build-1-17:

    name: Build and test (Elixir 1.17; Erlang 27)
    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libwxgtk3.0-gtk3-dev
        version: 1.0
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18.1
      with:
        elixir-version: '1.17.2'
        otp-version: '27.0.1'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: mix test
